#pragma once
#include <cstdint>
#include <memory>

/// @brief Standard gravity expressed in milligravity units.
#define GRAVITY_MG 1000.0f

/// @brief Scale used to convert Q1.14 values to floating-point values.
#define Q14_SCALE 16384.0f

/// @brief Nominal duration of one LSM6DSV16X timestamp tick. The value can be
/// corrected with INTERNAL_FREQ_FINE if sub-percent timing accuracy is needed.
inline constexpr float LSM_TIMESTAMP_TICK_SECONDS = 21.75e-6f;

namespace data
{

/// @brief Groups a quaternion, an acceleration vector and the rotated output.
struct RotationStruct
{
    /// @brief Quaternion real component.
    float qw;

    /// @brief Quaternion X imaginary component.
    float qx;

    /// @brief Quaternion Y imaginary component.
    float qy;

    /// @brief Quaternion Z imaginary component.
    float qz;

    /// @brief Accelerometer X-axis value.
    float ax;

    /// @brief Accelerometer Y-axis value.
    float ay;

    /// @brief Accelerometer Z-axis value.
    float az;

    /// @brief Rotated X-axis output value.
    float rOutX;

    /// @brief Rotated Y-axis output value.
    float rOutY;

    /// @brief Rotated Z-axis output value.
    float rOutZ;
};

/// @brief One synchronized IMU sample stored for motion processing.
struct SamplePacket
{
    /// @brief Raw 32-bit timestamp generated by the LSM6DSV16X.
    /// One tick is nominally 21.75 us. Unsigned subtraction handles wraparound.
    /// 4 bytes
    uint32_t timestamp_ticks;

    /// @brief Quaternions data obtained from IMU using built in SFLP
    /// Qw Qx Qy Qz  Q1.14 format
    /// 8 bytes
    int16_t q[4];

    /// @brief Acceleration data obtained from IMU in mg
    /// Ax, Ay, Az
    /// 6 bytes
    int16_t a[3];

    /// @brief Gravity vector data obtained from IMU in mg
    /// Gvx, Gvy, Gvz
    /// 6 bytes
    int16_t gv[3];
};
static_assert(sizeof(SamplePacket) == 24, "SamplePacket must be 24 bytes");

/// @brief Accelerometer bias calculated for the X, Y and Z sensor axes.
struct AccBiasVec3
{
    /// @brief ax bias
    int32_t axBias;

    /// @brief ay bias
    int32_t ayBias;

    /// @brief az bias
    int32_t azBias;
};
static_assert(sizeof(AccBiasVec3) == 12, "AccBiasVec3 must be 12 bytes");

} // namespace data
